name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
          persist-credentials: false

    # 生成静态文件
    - name: Build
      run: yarn install && yarn run docs:build

    # 部署到 GitHub Pages
    - name: Deploy
      # 使用别人写好的一个 action
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        # 打包后的文件部署到哪个分支上
        BRANCH: gh-pages
        # 打包后的文件在哪里
        FOLDER: docs/.vuepress/dist